### ISSUE TITLE
Can't update to TYPO3 V9.5.6 in Classic Mode

### ISSUE THREAD

**Issue by Treedent** [pagemachine/typo3-formlog#26]
When updating TYPO3 V9LTS to V9.5.6, the following error comes from formlog extension (1.1.7). Then I can't use the latest TYPO3 version without deactivating formlog extension : 

 Failed opening required 'phar:///var/www/web/typo3conf/ext/formlog//vendors.phar/vendor/autoload.php'

**Comment by mbrodala** [comment]
This has just been fixed with #23 and a new release will be made today.

**Comment by Treedent** [comment]
The problem persists with version 1.2.0.

Warning: Uncaught TYPO3\PharStreamWrapper\Exception: Executing phar:///var/www/web/typo3conf/ext/formlog/vendors.phar/vendor/autoload.php is denied in /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php:40 Stack trace: #0 /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): TYPO3\CMS\Core\IO\PharStreamWrapperInterceptor->assert('phar:///var/www...', 'stream_open') #1 /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert('phar:///var/www...', 'stream_open') #2 /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert('phar:///var/www...', 'stream_open') #3 /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/vendor/typo3/phar-stream-wrapper/src/PharStream in /var/www/clients/client36/web323/typo3_src/typo3_src-9.5.6/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php on line 40

Fatal error: TYPO3\CMS\Core\Utility\ExtensionManagementUtility::main(): Failed opening required 'phar:///var/www/web/typo3conf/ext/formlog/vendors.phar/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/clients/client36/web323/web/typo3conf/ext/formlog/ext_localconf.php on line 17

**Comment by mbrodala** [comment]
Can you do a little debugging in the mentioned `PharStreamWrapperInterceptor` to see what path is checked here after normalization?

Maybe @ohader has another idea.

**Comment by ohader** [comment]
Hm... is the extension directory symlinked to some directory outside of `typo3conf/ext`, e.g. `project/public/typo3conf/ext/formlog -> project/extensions/formlog`?

**Comment by Treedent** [comment]
In my case, no, Formlog is in typo3conf/ext/

**Comment by Treedent** [comment]
The path used by phar has a symlink. In my case, 
phar:///var/www/web/typo3conf/ext/formlog/vendors.phar/vendor/autoload.php
"web" is a symlink. The real path is : 
/var/www/clients/client36/web323/web/typo3conf/ext/formlog/vendors.phar/vendor/autoload.php
Maybe it brokes on the symlink ?

**Comment by mbrodala** [comment]
@Treedent can you try if [this change in TYPO3](https://review.typo3.org/c/Packages/TYPO3.CMS/+/60739) fixes the issue for you?

**Comment by Treedent** [comment]
Sounds good, the phar path is well resolved with this patch.
Thank you.

**Comment by mbrodala** [comment]
Thanks, I've forwarded your test result to the mentioned change. You are free to vote for yourself, of course. ;-)
